[target.aarch64-linux-android]
linker = "aarch64-linux-android33-clang"
rustflags = [
    "-C", "link-arg=-landroid",
    "-C", "link-arg=-llog",
    "-C", "link-arg=-lOpenSLES",
]

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi33-clang"
rustflags = [
    "-C", "link-arg=-landroid",
    "-C", "link-arg=-llog",
    "-C", "link-arg=-lOpenSLES",
]

[target.x86_64-linux-android]
linker = "x86_64-linux-android33-clang"
rustflags = [
    "-C", "link-arg=-landroid",
    "-C", "link-arg=-llog",
    "-C", "link-arg=-lOpenSLES",
]
